export default {
  en: {
    home: 'Home',
    ranking: 'Ranking',
    search: 'Search',
    newest: 'Newest',
    myPage: 'My Page',
    illustration: 'Illustration',
    illust: 'Illust',
    manga: 'Manga',
    illustManga: 'Illust/Manga',
    user: 'User',
    searchPlaceHolder: 'Enter keyword',
    searchUserPlaceHolder: 'Enter nickname',
    searchHistory: 'Search History',
    clearSearchHistory: 'Clear Search History',
    displayOptions: 'Display Options',
    following: 'Following',
    followingPublic: 'Following (Public)',
    followingPrivate: 'Following (Private)',
    follower: 'Follower',
    illustrationPublic: 'Illustration (Public)',
    illustrationPrivate: 'Illustration (Private)',
    myPixiv: 'My Pixiv',
    myWorks: 'Submitted Works',
    connection: 'Connection',
    collection: 'Collection',
    browsingHistory: 'Browsing History',
    settings: 'Settings',
    feedback: 'Feedback',
    public: 'Public',
    private: 'Private',
    signup: 'Sign Up',
    login: 'Login',
    logout: 'Logout',
    emailOrPixivId: 'Email address / pixiv ID',
    password: 'Password',
    validateEmailOrPixivId: 'Please enter your email address or pixiv ID',
    validatePassword: 'Please enter your password',
    ok: 'OK',
    cancel: 'Cancel',
    day_ranking: 'Daily',
    week_ranking: 'Weekly',
    month_ranking: 'Monthly',
    day_male_ranking: 'Male',
    day_female_ranking: 'Female',
    week_rookie_ranking: 'Rookie',
    week_original_ranking: 'Original',
    day_r18_ranking: 'R18 Daily',
    day_male_r18_ranking: 'R18 Male',
    day_female_r18_ranking: 'R18 Female',
    week_r18_ranking: 'R18 Weekly',
    week_r18g_ranking: 'R18G Weekly',
    past_ranking: 'Past Ranking',
    followUserNullState: 'You are not following anyone yet',
    newWorkFollowNullState: 'Follow your favourite users to keep up to date with their latest works',
    findRecommendedUsers: 'Recommended Users',
  },
  ja: {
    home: 'ホーム',
    ranking: 'ランキング',
    search: '検索',
    newest: '新着',
    myPage: 'マイページ',
    illustration: 'イラスト',
    illust: 'イラスト',
    manga: 'マンガ',
    illustManga: 'イラスト・マンガ',
    user: 'ユーザー',
    searchPlaceHolder: 'キーワードを入力',
    searchUserPlaceHolder: 'ニックネームを入力',
    searchHistory: '検索履歴',
    clearSearchHistory: '履歴をクリア',
    displayOptions: '表示オプション',
    following: 'フォロー',
    followingPublic: 'フォロー (公開)',
    followingPrivate: 'フォロー (非公開)',
    follower: 'フォロワー',
    illustrationPublic: 'イラスト (公開)',
    illustrationPrivate: 'イラスト (非公開)',
    myPixiv: 'マイピク',
    myWorks: '自分の作品',
    connection: 'つながり',
    collection: 'コレクション',
    browsingHistory: '閲覧履歴',
    settings: '設定',
    feedback: 'フィードバック',
    public: '公開',
    private: '非公開',
    signup: '新規登録',
    login: 'ログイン',
    logout: 'ログアウト',
    emailOrPixivId: 'メールアドレス / pixiv ID',
    password: 'パスワード',
    validateEmailOrPixivId: 'pixiv ID、またはメールアドレスが未記入です',
    validatePassword: 'パスワードが未記入です',
    ok: 'OK',
    cancel: 'キャンセル',
    day_ranking: 'デイリー',
    week_ranking: 'ウィークリー',
    month_ranking: 'マンスリー',
    day_male_ranking: '男子に人気',
    day_female_ranking: '女子に人気',
    week_rookie_ranking: 'ルーキー',
    week_original_ranking: 'オリジナル',
    day_r18_ranking: 'R18 デイリー',
    day_male_r18_ranking: 'R18 男子に人気',
    day_female_r18_ranking: 'R18 女子に人気',
    week_r18_ranking: 'R18 ウィークリー',
    week_r18g_ranking: 'R18G ウィークリー',
    past_ranking: '過去のランキング',
    followUserNullState: 'ユーザーをフォローしていません',
    newWorkFollowNullState: '好きなユーザーをフォローして最新投稿を追いかけましょう',
    findRecommendedUsers: 'オススメのユーザーを見る',
  },
};
